// <auto-generated />
using FilegaJobs.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FilegaJobs.Migrations
{
    [DbContext(typeof(FilegaDbContext))]
    [Migration("20221002133217_AlterSeedJobsTable")]
    partial class AlterSeedJobsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FilegaJobs.Models.Jobs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("salary")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Job");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "xxxxxxx",
                            Name = "Accountant",
                            salary = 1000
                        },
                        new
                        {
                            ID = 2,
                            Description = "xxxxxxx",
                            Name = "Sectretary",
                            salary = 100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
